"Resource/UI/gamepausepanel.res"
{
	"Paused_Background"
	{
		"ControlName"	"CImagePanel"
		"fieldName"		"Paused_Background"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"-1"
		"wide"			"260"
		"tall"			"196"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/color_panel_red"
		"scaleImage"	"1"
	}
	
	"Paused_Title"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"Paused_Title"
		"font"			"DefaultLarge"
		"xpos"			"0"
		"ypos"			"60"
		"wide"			"260"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Paused"
		"textAlignment"	"Center"
		"dulltext"		"0"
		"brighttext"	"0"
	}
	
	"Paused_Message"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"Paused_Message"
		"font"			"Default"
		"xpos"			"0"
		"ypos"			"83"
		"wide"			"260"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"The game has been paused"
		"textAlignment"	"Center"
		"dulltext"		"0"
		"brighttext"	"0"
	}
	
	"Paused_Countdown"
	{	
		"ControlName"	"CExLabel"
		"fieldName"		"Paused_Countdown"
		"font"			"DefaultLarge"
		"xpos"			"40"
		"ypos"			"73"
		"wide"			"260"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"3"
		"textAlignment"	"West"
		"dulltext"		"0"
		"brighttext"	"0"
	}
}