"Resource/UI/HudMenuVoiceSelection.res"
{
	"HudMenuVoiceSelection"
	{
		"fieldName"		"HudMenuVoiceSelection"
		"visible"		"1"
		"enabled"		"1"
		"xpos"			"c-200"
		"ypos"			"c-200"
		"wide"			"400"
		"tall"			"400"
		"PaintBackgroundType"	"0"
	}
	"MainBackground"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"MainBackground"
		"xpos"			"c-250"
		"ypos"			"c-250"
		"zpos"			"0"
		"wide"			"100"
		"tall"			"100"
		"visible"		"0"
		"enabled"		"1"
		"bgcolor_override" "0 0 0 200"
		"PaintBackgroundType"	"2"
	}
	"TitleLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TitleLabel"
		"font"			"HudFontSmallestBold"
		"xpos"			"c-300"
		"ypos"			"c-220"
		"zpos"			"3"
		"wide"			"200"
		"tall"			"40"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"COMMUNICATION MENU"
		"textAlignment"	"center"
		"fgcolor"		"TanLight"
	}
	"ItemLabel1"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ItemLabel1"
		"font"			HudFontSmallest
		"xpos"			"160"
		"ypos"			"90"
		"zpos"			"1"
		"wide"			"60"
		"tall"			"40"
		"centerwrap"	"1"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Option 1"
		"textAlignment"	"center"
		"fgcolor"		"TanLight"
	}
	"NumberLabel1"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"NumberLabel1"
		"font"			"HudMenuNumberFont"
		"xpos"			"160"
		"ypos"			"105"
		"zpos"			"1"
		"wide"			"60"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"1"
		"textAlignment"	"center"
		"fgcolor"		"TanDark"
	}
	"ItemLabel2"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ItemLabel2"
		"font"			HudFontSmallest
		"xpos"			"224"
		"ypos"			"113"
		"zpos"			"1"
		"wide"			"60"
		"tall"			"40"
		"centerwrap"	"1"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Option 2"
		"textAlignment"	"center"
		"fgcolor"		"TanLight"
	}
	"NumberLabel2"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"NumberLabel2"
		"font"			"HudMenuNumberFont"
		"xpos"			"224"
		"ypos"			"128"
		"zpos"			"1"
		"wide"			"60"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"2"
		"textAlignment"	"center"
		"fgcolor"		"TanDark"
	}
	"ItemLabel3"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ItemLabel3"
		"font"			HudFontSmallest
		"xpos"			"258"
		"ypos"			"172"
		"zpos"			"1"
		"wide"			"60"
		"tall"			"40"
		"centerwrap"	"1"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Option 3"
		"textAlignment"	"center"
		"fgcolor"		"TanLight"
	}
	"NumberLabel3"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"NumberLabel3"
		"font"			"HudMenuNumberFont"
		"xpos"			"258"
		"ypos"			"187"
		"zpos"			"1"
		"wide"			"60"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"3"
		"textAlignment"	"center"
		"fgcolor"		"TanDark"
	}
	"ItemLabel4"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ItemLabel4"
		"font"			HudFontSmallest
		"xpos"			"246"
		"ypos"			"240"
		"zpos"			"1"
		"wide"			"60"
		"tall"			"40"
		"centerwrap"	"1"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Option 4"
		"textAlignment"	"center"
		"fgcolor"		"TanLight"
	}
	"NumberLabel4"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"NumberLabel4"
		"font"			"HudMenuNumberFont"
		"xpos"			"246"
		"ypos"			"255"
		"zpos"			"1"
		"wide"			"60"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"4"
		"textAlignment"	"center"
		"fgcolor"		"TanDark"
	}
	"ItemLabel5"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ItemLabel5"
		"font"			HudFontSmallest
		"xpos"			"194"
		"ypos"			"284"
		"zpos"			"1"
		"wide"			"60"
		"tall"			"40"
		"centerwrap"	"1"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Option 5"
		"textAlignment"	"center"
		"fgcolor"		"TanLight"
	}
	"NumberLabel5"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"NumberLabel5"
		"font"			"HudMenuNumberFont"
		"xpos"			"194"
		"ypos"			"299"
		"zpos"			"1"
		"wide"			"60"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"5"
		"textAlignment"	"center"
		"fgcolor"		"TanDark"
	}
	"ItemLabel6"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ItemLabel6"
		"font"			HudFontSmallest
		"xpos"			"126"
		"ypos"			"284"
		"zpos"			"1"
		"wide"			"60"
		"tall"			"40"
		"centerwrap"	"1"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Option 6"
		"textAlignment"	"center"
		"fgcolor"		"TanLight"
	}
	"NumberLabel6"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"NumberLabel6"
		"font"			"HudMenuNumberFont"
		"xpos"			"126"
		"ypos"			"299"
		"zpos"			"1"
		"wide"			"60"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"6"
		"textAlignment"	"center"
		"fgcolor"		"TanDark"
	}
	"ItemLabel7"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ItemLabel7"
		"font"			HudFontSmallest
		"xpos"			"74"
		"ypos"			"240"
		"zpos"			"1"
		"wide"			"60"
		"tall"			"40"
		"centerwrap"	"1"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Option 7"
		"textAlignment"	"center"
		"fgcolor"		"TanLight"
	}
	"NumberLabel7"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"NumberLabel7"
		"font"			"HudMenuNumberFont"
		"xpos"			"74"
		"ypos"			"255"
		"zpos"			"1"
		"wide"			"60"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"7"
		"textAlignment"	"center"
		"fgcolor"		"TanDark"
	}
	"ItemLabel8"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ItemLabel8"
		"font"			HudFontSmallest
		"xpos"			"62"
		"ypos"			"172"
		"zpos"			"1"
		"wide"			"60"
		"tall"			"40"
		"centerwrap"	"1"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Option 8"
		"textAlignment"	"center"
		"fgcolor"		"TanLight"
	}
	"NumberLabel8"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"NumberLabel8"
		"font"			"HudMenuNumberFont"
		"xpos"			"62"
		"ypos"			"187"
		"zpos"			"1"
		"wide"			"60"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"8"
		"textAlignment"	"center"
		"fgcolor"		"TanDark"
	}
	"ItemLabel9"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ItemLabel9"
		"font"			HudFontSmallest
		"xpos"			"96"
		"ypos"			"113"
		"zpos"			"1"
		"wide"			"60"
		"tall"			"40"
		"centerwrap"	"1"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Option 9"
		"textAlignment"	"center"
		"fgcolor"		"TanLight"
	}
	"NumberLabel9"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"NumberLabel9"
		"font"			"HudMenuNumberFont"
		"xpos"			"96"
		"ypos"			"128"
		"zpos"			"1"
		"wide"			"60"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"9"
		"textAlignment"	"center"
		"fgcolor"		"TanDark"
	}
}
