#!/bin/bash

set -euo pipefail

# make sure ccache dir is available
my_ccache_dir=${CCACHE_DIR:-$HOME/.ccache}
mkdir -p ${my_ccache_dir}

function run_in_sniper() {
    script_file=$(basename -- "$script")
    check_env=$(sha256sum -- "$script" | cut -d " " -f 1)

    if [[ ! -f /run/.containerenv ]]; then
        # Check if podman exists
        if ! command -v podman &> /dev/null; then
            echo "Error: podman is not installed. Exiting..."
            exit 1
        fi

        # Let's say we run as /home/mcoms/tc2/src/myscript
        # We want to mount /home/mcoms/tc2, and then launch
        # src/myscript inside of that.
        #
        # The below achieves that.
        mod_src_dir=$(pwd)
        mod_src_dir_name=$(basename -- "$mod_src_dir")
        mod_base_dir=$(dirname -- "$mod_src_dir")

        if [[ ! -v GITHUB_ACTIONS ]]; then
            GITHUB_ACTIONS=""
        fi

        if [ -z ${GITHUB_ACTIONS} ]; then
            USERNS="--userns=keep-id"
        else
            USERNS=""
        fi

        image="registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest"
        echo "Running script inside $image"
        # you need a recent version of podman, tested on 5.6
        exec podman run \
            --env "$check_env=$script_file" \
            --env "CCACHE_DIR=${my_ccache_dir}" \
            --env "GITHUB_ACTIONS=${GITHUB_ACTIONS}" \
            $USERNS \
            --rm -it \
            --mount type=bind,\"source="${my_ccache_dir}"\",\"target="${my_ccache_dir}"\" \
            --mount type=bind,\"source="${mod_base_dir}"\",\"target="/tc2/"\" \
            "$image" \
            /tc2/"$mod_src_dir_name"/"$script_file" \
            "$@"
    fi

    if [[ $(printenv -- "$check_env") != "$script_file" ]]; then
        echo "Can't run in a nested container setup. Sorry! :("
        exit 1
    fi
}
