name: Build - Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - name: Setup Butler
        id: setup-butler
        run: |
          sudo apt-get install unzip
          mkdir -p ~/.local/bin
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip -d ~/.local/bin/ butler.zip
          chmod +x ~/.local/bin/butler
      - name: Build dist
        id: build-dist
        env:
          CCACHE_DIR: ${{ github.workspace }}/.ccache
        run: |
          mkdir -p $CCACHE_DIR
          ./src/buildallprojects
          ./game_clean/copy.sh
      - name: Push to Itch
        id: itch
        run: ./game_clean/push.sh
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: game
          path: |
            game_dist
      - name: Archive debug info
        uses: actions/upload-artifact@v4
        with:
          name: game-debug-info
          path: |
            game_dist_debug
